### PR TITLE
HSDO-935 7.x-3.3 Tag

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- 7.x-3.3 Release

# Release Notes
- HSDO-918 Branding overlay for hero block
- Bug fix for curtain reveal on safari

# Needed By (Date)
- End of Sprint

# Urgency
- Low

### CODE REVIEW

**Comment by boznik** [comment]
@pookmish , i think the README should get updated too, right?

**Comment by pookmish** [comment]
Good point! thanks

**Comment by pookmish** [comment]
Updated

**Comment by boznik** [comment]
unless i missed something, the version of modules/ds_bean_fields changed too, but that one isn't updated in the readme but should be right?

**Comment by pookmish** [comment]
ahh. i didnt even notice that line. 👍

**Pull request merged**
