### PR TITLE
Added module enable for stanford_field_formatters

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW
# Summary
- Added module_enable for stanford_field_formatters

# Needed By (Date)
- Now

# Urgency
- High urgency

# Steps to Test

1. checkout branch, run database updates.
2. check if stanford_field_formatters is enabled.

### CODE REVIEW

**Comment by jbickar** [comment]
1. Confirmed that the module gets enabled when it exists.

**Comment by jbickar** [comment]
When `stanford_field_formatters` is not available:

```
% drush -y updb
Stanford Bean Types requires this module. (Currently using Unresolved dependency stanford_field_formatters (Missing))[warning]
Stanford Bean Types Permissions requires this module. (Currently using Unresolved dependency                         [warning]
stanford_field_formatters (Missing))
 Stanford_bean_types  7202  Move links to field collection.  
 Stanford_bean_types  7203  Delete old fields.
Do you wish to run all pending updates? (y/n): y
4 byte UTF-8 for mysql is not activated, but it is supported on your system. It is recommended that you enable this  [warning]
to allow 4-byte UTF-8 input such as emojis, Asian symbols and mathematical symbols to be stored correctly. See the
documentation on adding 4 byte UTF-8 support for more information. (Currently using Database 4 byte UTF-8 support Not
enabled)
Stanford Bean Types requires this module. (Currently using Unresolved dependency stanford_field_formatters (Missing))[warning]
Stanford Bean Types Permissions requires this module. (Currently using Unresolved dependency                         [warning]
stanford_field_formatters (Missing))
Attempt to create a field of unknown type <em class="placeholder">fontawesome_icon</em>.                             [error]
Performed update: stanford_bean_types_update_7202                                                                    [ok]
'all' cache was cleared.                                                                                             [success]
Finished performing updates.  
```

Re-running `drush updb` gives the same output.

I think this should provide different guidance if the module is not available.

**Comment by pookmish** [comment]
How is this. it seems that throwing an error in a called function doesn't kill the update function itself.
```
drush updb -y
 Stanford_bean_types  7202  Move links to field collection.
Do you wish to run all pending updates? (y/n): y
Could not enable stanford_field_formatters module. Please check that the module exists.                                                                                                                                                                              [error]
Performed update: stanford_bean_types_update_7202                                                                                                                                                                                                                    [ok]
'all' cache was cleared.                                                                                                                                                                                                                                             [success]
Finished performing updates.
```

**Comment by jbickar** [comment]
We'll need `stanford_field_formatters` added to all the products in `stanford-jumpstart-deployer` and in `Stanford-Drupal-Profile`. I'll send PRs.

**Comment by jbickar** [comment]
Testing this now.

**Comment by jbickar** [comment]
1. When `stanford_field_formatters` does not exist, updating `stanford_bean_types` to this branch and running `drush updb` gives the error message "Could not enable stanford_field_formatters module. Please check that the module exists." and the schema stays at `7201`. This is good.
2. When we make `stanford_field_formatters` available, and run `drush updb`, update `7202` and `7203` both run. This is also good.

**Comment by jbickar** [comment]
FYI @sherakama

**Comment by sherakama** [comment]
Nice work. Good approach.

**Pull request merged**
