### PR TITLE
HSDO-557 HSDO-873 Refactored fields to use view modes instead of preprocessing

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Added fields to allow for text/number input on icon grid bean type

# Needed By (Date)
- 5/24

# Steps to Test

1. Checkout branch
2. update db & revert feature
3. add new icon grid bean type
4. choose 'text/number' from the icon style (choose the other two options as well to verfiy)
5. validate the text or number you input shows with a color background.

# Affected Projects or Products
- https://github.com/SU-SWS/linky_clicky/pull/154

will need to Merge tests, change travis branch, then squash and merge when approved.

### CODE REVIEW

**Comment by boznik** [comment]
@pookmish did you see the failed travis build?

**Comment by pookmish** [comment]
ya it passed once the commit before i assigned it to you. i gotta revisit tomorrow

**Comment by boznik** [comment]
also getting this error after creating the block:
Notice: Undefined index: subset in stanford_field_formatters_field_widget_form() (line 593 of  
                                        /Users/ggarvey/www/jsa/sites/all/modules/stanford/stanford_field_formatters/stanford_field_for

**Comment by pookmish** [comment]
Doesnt work to have a debug command in a template file. haha. Latest version of this and stanford_field_formatters should work

**Pull request merged**
