### PR TITLE
SOE-1651: Add call to action modules

### PR DESCRIPTION
**Pull request by cjwest**
# NOT READY FOR REVIEW

# Summary
- This PR is for the call-to-action blocks. This is for the 2.x branch, and _SoE needs the 2.x branch_. 

# Needed By (Date)
ASAPP (As soon as practically possible)

# Urgency
We need to get stylin'

# Steps to Test
 
## To test:
1. Enable "Stanford Bean Call-to-Action" and "Stanford Bean  Call-to-Action Administration" module
2. Revert feature if necessary
3. On the "Manage Display" form adjust fields as necessary. (See Attachments)
4. Create a  **Call-to-Action** Bean
5. Verify the help text is displaying properly. See [SOE-1864](https://stanfordits.atlassian.net/browse/SOE-1864) and [SOE-1865](https://stanfordits.atlassian.net/browse/SOE-1865)
6.  Navigate to **admin/manage/content** and verify it displays properly in the mange content view
7. Click on **Manage Call-to-Action Blocks** menu item
8. Verify it shows up on the Manage content page and that the page provides expected options
9. Place block and verify display and responsive behavior

# Affected Projects or Products
SoE

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOE-1864
- https://stanfordits.atlassian.net/browse/SOE-1865
- https://stanfordits.atlassian.net/browse/SOE-1651

- Anyone who should be notified? @boznik, @josephgknox 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

# Attachments
Here's how to adjust the _Manage Display_

screen shot 2017-06-20 at 11 09 03

### CODE REVIEW

**Comment by boznik** [comment]
looks good, let's get it styled before the merge.

**Comment by josephgknox** [comment]
@cjwest if this is ready, feel free to pass the related ticket to me for the front-end work.

**Comment by cjwest** [comment]
@josephgknox 
She's all yours!

I'd like to get the _Style_ site set up first so you can do your work there...

**Comment by josephgknox** [comment]
@boznik ready to merge.

**Comment by josephgknox** [comment]
@boznik was there more work you were hoping to see on this, or are we good to go?

**Comment by boznik** [comment]
@cjwest i'm still getting accent color on cta block even though it is disabled in manage display???

**Comment by cjwest** [comment]
Caryl,
remove field_s_cta_color!

**Comment by cjwest** [comment]
Okay Mr. @boznik,
We have an update hook. Thanks for the help with that!

**Comment by sherakama** [comment]
It's time to stop and go enjoy the longest day of the year. Today is a patio day where you linger in the good weather and no in font of a computer.

**Comment by sherakama** [comment]
It's time to stop and go enjoy the longest day of the year. Today is a patio day where you linger in the good weather and not in front of a computer.

**Comment by boznik** [comment]
i really appreciate how @sherakama watches out for us regardless of a complex pr or giving tribute to ourselves revolving around the sun(seriously, ty)

**Comment by josephgknox** [comment]
:o)

**Comment by cjwest** [comment]
Okay Mr. @boznik,
We now have the update hook _and_ help text! FTW!

**Comment by cjwest** [comment]
@boznik,

It looks like I pulled in some unintended changes. Would like to go through that with you.

**Pull request closed without merging**
